### ISSUE TITLE
panic interface conversion: ast.Expr is *ast.SelectorExpr, not *ast.Ident

### ISSUE THREAD

**Issue by hawkingrei** [polyfloyd/go-errorlint#42]
```
compilepkg: panic: interface conversion: ast.Expr is *ast.SelectorExpr, not *ast.Ident

goroutine 264 [running]:
github.com/polyfloyd/go-errorlint/errorlint.assigningCallExprs(0xc0004c0000, 0xc000ae0e00)
	external/com_github_polyfloyd_go_errorlint/errorlint/allowed.go:160 +0x5cb
github.com/polyfloyd/go-errorlint/errorlint.isAllowedErrorComparison(0xc0004c0000, 0xc00157d920?)
	external/com_github_polyfloyd_go_errorlint/errorlint/allowed.go:91 +0x185
github.com/polyfloyd/go-errorlint/errorlint.LintErrorComparisons(0xc000e22d70?, 0xc0004c0000)
	external/com_github_polyfloyd_go_errorlint/errorlint/lint.go:182 +0x1eb
github.com/polyfloyd/go-errorlint/errorlint.run(0xc00209a410)
	external/com_github_polyfloyd_go_errorlint/errorlint/analysis.go:40 +0x6d
github.com/pingcap/tidb/build/linter/util.SkipAnalyzer.func1(0xc00209a340)
	build/linter/util/util.go:139 +0x11f
main.(*action).execOnce(0xc000527cb0)
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:303 +0x8df
sync.(*Once).doSlow(0x0?, 0x0?)
	GOROOT/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	GOROOT/src/sync/once.go:65
main.(*action).exec(0x0?)
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:247 +0x3d
main.execAll.func1(0x0?)
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:241 +0x54
created by main.execAll
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:239 +0x47
INFO: Elapsed time: 4.440s, Critical Path: 3.66s
```

**Comment by polyfloyd** [comment]
Thanks for reporting this! Could you post a snippet of code that triggers this issue?

**Comment by hawkingrei** [comment]
In fact, I am adding errorlint into the tidb by nogo. Here is an [PR](https://github.com/pingcap/tidb/pull/43660#diff-4684e52b2f07cacef882d7349c4c93909074491cfb9594f27f8e7ebf717ca0a5)
